"""empty message

Revision ID: d8e515997d8a
Revises: 001_initial
Create Date: 2025-12-06 01:11:12.666066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e515997d8a'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use IF EXISTS variants so migrations don't fail when objects are already absent
    op.execute(f"ALTER TABLE bookings DROP CONSTRAINT IF EXISTS {op.f('bookings_booking_number_key')}")
    op.execute(f"DROP INDEX IF EXISTS {op.f('ix_bookings_dates')}")
    op.execute(f"ALTER TABLE bookings DROP CONSTRAINT IF EXISTS {op.f('unique_bk_num')}")
    op.execute(f"ALTER TABLE guests DROP CONSTRAINT IF EXISTS {op.f('guests_email_key')}")
    op.execute(f"DROP INDEX IF EXISTS {op.f('ix_rooms_room_type_id')}")
    op.execute(f"ALTER TABLE rooms DROP CONSTRAINT IF EXISTS {op.f('rooms_number_key')}")
    op.execute(f"ALTER TABLE users DROP CONSTRAINT IF EXISTS {op.f('users_username_key')}")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('rooms_number_key'), 'rooms', ['number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_rooms_room_type_id'), 'rooms', ['room_type_id'], unique=False)
    op.create_unique_constraint(op.f('guests_email_key'), 'guests', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('unique_bk_num'), 'bookings', ['booking_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_bookings_dates'), 'bookings', ['check_in', 'check_out'], unique=False)
    op.create_unique_constraint(op.f('bookings_booking_number_key'), 'bookings', ['booking_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
